# Generated by Django 3.1.3 on 2020-11-23 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0003_auto_20201123_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='horse',
            new_name='Account',
        ),
    ]
