# Generated by Django 3.1.3 on 2020-11-23 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_auto_20201123_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.FileField(upload_to='grading')),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=69)),
                ('description', models.CharField(max_length=640)),
                ('code', models.CharField(default='7g8zav', max_length=6)),
                ('responses', models.ManyToManyField(related_name='answers', to='grading.Response')),
                ('students', models.ManyToManyField(related_name='responders', to='grading.Account')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grader', to='grading.account')),
            ],
        ),
    ]
