# Generated by Django 3.1.3 on 2020-11-23 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_assignment_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.FileField(blank=True, upload_to='grading')),
                ('score', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='grading.account')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='zpj35z', max_length=6),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='assignment',
            name='responders',
            field=models.ManyToManyField(blank=True, related_name='volunteer', to='grading.Responder'),
        ),
    ]
