# Generated by Django 3.1.3 on 2020-11-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_auto_20201123_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='q8e6cm', max_length=6),
        ),
    ]
