# Generated by Django 3.1.3 on 2020-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_auto_20201123_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='wq6ess', max_length=6),
        ),
        migrations.AlterField(
            model_name='responder',
            name='work',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
