# Generated by Django 3.1.3 on 2020-11-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_auto_20201123_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='eegv1y', max_length=6),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ManyToManyField(related_name='grader', to='grading.Account'),
        ),
    ]
