# Generated by Django 3.1.3 on 2020-11-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_auto_20201124_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='jz4p2e', max_length=6),
        ),
        migrations.AlterField(
            model_name='responder',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='grading.account'),
        ),
    ]
