# Generated by Django 3.1.3 on 2020-11-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_auto_20201124_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='3jsbyu', max_length=6),
        ),
        migrations.AlterField(
            model_name='responder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='grading.account'),
        ),
    ]
