# Generated by Django 3.1.3 on 2020-11-28 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_auto_20201126_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.FileField(blank=True, upload_to='')),
                ('score', models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='responders',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='code',
            field=models.CharField(default='bqfp1x', max_length=6),
        ),
        migrations.DeleteModel(
            name='Responder',
        ),
        migrations.AddField(
            model_name='response',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='grading.assignment'),
        ),
        migrations.AddField(
            model_name='response',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='grading.account'),
        ),
    ]
